### ISSUE TITLE
Missing link to the Explain web project

### ISSUE THREAD

**Issue by Svdwege** [AEAEmbedded/ESE_PROG#2]
The code for the explain web project which is linked in the [HAN_Hackaton_Prog_6_2025.pdf](https://github.com/AEAEmbedded/ESE_PROG/blob/main/HAN_Hackaton_Prog_6_2025.pdf) is is missing a link to the git repository containing the code for this project 
The link to the repository is [https://github.com/Dobutamine/explain-web](https://github.com/Dobutamine/explain-web)

**Comment by jakorten** [comment]
Fixed: Added to README.md
